Module 22.5/finfriend/accounts/urls.py
from django.urls import path,include
from .views import UserRegistrationView,UserLoginView,UserBankAccountUpdateView
from . import views

urlpatterns = [
    path('register/',UserRegistrationView.as_view(),name='register'),
    path('login/',UserLoginView.as_view(),name='login'),
    path('logout/',views.user_logout,name='logout'),
    path('profile/', UserBankAccountUpdateView.as_view(), name='profile' )
]

Module 22.5/finfriend/finfriend/urls.py
from django.contrib import admin
from django.urls import path,include
from core.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',HomeView.as_view(),name='home'),
    path('accounts/',include('accounts.urls')),
    path('transactions/',include('transactions.urls'))
]

Module 22.5/finfriend/transactions/urls.py
from django.urls import path
from .views import DepositMoneyView,WithdrawMoneyView,PayLoanView,LoanListView,LoanRequestView,TransactionReportView,TransferMoneyView

urlpatterns = [
    path('deposit/',DepositMoneyView.as_view(),name='deposit_money'),
    path('withdraw/',WithdrawMoneyView.as_view(),name='withdraw_money'),
    path('loan/<int:loan_id>',PayLoanView.as_view(),name='loan_pay'),
    path('loans/',LoanListView.as_view(),name='loan_list'),
    path('loan_request/',LoanRequestView.as_view(),name='loan_request'),
    path('report/',TransactionReportView.as_view(),name='transaction_report'),
    path("transfer/", TransferMoneyView.as_view(), name="transfer_money"),
]

Module 22.5/finfriend/transactions/models.py
from django.db import models
from accounts.models import UserBankAccount
from .constants import TRANSACTION_TYPE 

# Create your models here.
class Transactions(models.Model):
    account=models.ForeignKey(UserBankAccount,related_name='transactions',on_delete=models.CASCADE)

    amount=models.DecimalField(max_digits=12,decimal_places=2)
    balance_after_transaction=models.DecimalField(max_digits=12, decimal_places=2)
    transaction_type=models.IntegerField(choices=TRANSACTION_TYPE,null=True)
    timestamp=models.DateTimeField(auto_now_add=True)
    loan_approve=models.BooleanField(default=False)
    receiver_account = models.IntegerField(default=1)

    class Meta:
        ordering=['timestamp']

class Bank(models.Model):
    name = models.CharField(max_length=200,default='bankrupt',null=True,blank=True)
    is_bankrupt = models.BooleanField(default=False)

Module 22.5/finfriend/transactions/forms.py
from django import forms
from .models import Transactions,Bank

class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transactions
        fields = ['amount','transaction_type']

        #transaction type customer ar edit korar option off kore dicchi
    def __init__(self,*args,**kwargs):
        self.account = kwargs.pop('account')
        super().__init__(*args,**kwargs)
        self.fields['transaction_type'].disabled = True
        self.fields['transaction_type'].widget = forms.HiddenInput() #hidden from user

    def save(self,commit=True):
        self.instance.account = self.account
        self.instance.balance_after_transaction = self.account.balance
        return super().save()
        
class DepositForm(TransactionForm):
    def clean_amount(self): #amount k filter korbo
        min_deposit_amount =100
        amount=self.cleaned_data.get('amount') #amount value from user filled form
        if amount < min_deposit_amount:
            raise forms.ValidationError(f'You need to deposit at least {min_deposit_amount}tk')
        return amount
    
class WithdrawForm(TransactionForm):
    def clean_amount(self):
        account=self.account
        min_withdraw_amount=100
        max_withdraw_amount=20000
        balance=account.balance
        amount=self.cleaned_data.get('amount')
        if amount<min_withdraw_amount :
            raise forms.ValidationError(f'You need to withdraw at least {min_withdraw_amount}tk')
        if amount>max_withdraw_amount:
            raise forms.ValidationError(f'You cannot withdraw more than {max_withdraw_amount}tk')
        if amount>balance:
            raise forms.ValidationError(f'You have {balance}tk in your account.You cannot withdraw more than {balance}tk')
        return amount
    
class LoanRequestForm(TransactionForm):
    def clean_amount(self):
        amount=self.cleaned_data.get('amount')
        return amount

class TransferForm(TransactionForm):
    class Meta:
        model = Transactions
        fields = ['amount','transaction_type','receiver_account']

    def check_bankruptcy(self):
        bank = Bank.objects.first()
        if bank and bank.is_bankrupt:
            raise forms.ValidationError('The bank is bankrupt, no withdrawals allowed.')
        
    def clean_amount(self):
       amount=self.cleaned_data.get('amount')
       if amount > self.account.balance:
           raise forms.ValidationError(f'You do not have sufficient balance.Transfer less or equal to {self.account.balance}tk.')
       return amount 

Module 22.5/finfriend/transactions/views.py
from http.client import HTTPResponse
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.views.generic import CreateView,ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Transactions
from .forms import DepositForm,WithdrawForm,LoanRequestForm,TransferForm
from .constants import TRANSACTION_TYPE,DEPOSIT, TRANSFER,WITHDRAW,LOAN,LOAN_PAID
from django.contrib import messages
from django.http import HttpResponse
from datetime import datetime
from django.db.models import Sum
from django.shortcuts import get_object_or_404,render,redirect
from django.views import View
from django.urls import reverse_lazy
from accounts.models import UserBankAccount

class TransactionCreateMixin(LoginRequiredMixin,CreateView):
    template_name= 'transactions/transaction_form.html'
    model_name=Transactions
    title=''
    success_url=reverse_lazy('transaction_report')
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({
            'account': self.request.user.account
        })
        return kwargs
    
    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context.update({
            'title': self.title,
        })
        return context

class DepositMoneyView(TransactionCreateMixin):
    form_class=DepositForm
    title='Deposit' #user j title dekhbe page ar tab ay

    def get_initial(self):
        initial={'transaction_type':DEPOSIT }
        return initial
    
    def form_valid(self, form):
        amount=form.cleaned_data.get('amount')
        account=self.request.user.account
        account.balance+=amount
        account.save(
            update_fields=['balance']
        )
        messages.success(self.request,f"{amount}tk was deposited successfully")
        return super().form_valid(form)

class WithdrawMoneyView(TransactionCreateMixin):
    form_class=WithdrawForm
    title='Withdraw Money'

    def get_initial(self):
        initial={'transaction_type':WITHDRAW}
        return initial
    
    def form_valid(self, form):
        amount=form.cleaned_data.get('amount')
        account=self.request.user.account
        account.balance-=amount
        account.save(
            update_fields=['balance']
        )
        messages.success(self.request,f"{amount}tk was withdrawn successfully")
        return super().form_valid(form)

class LoanRequestView(TransactionCreateMixin):
    form_class=LoanRequestForm
    title='Request For Loan'

    def get_initial(self):
        initial={'transaction_type':LOAN }
        return initial
    
    def form_valid(self, form):
        amount=form.cleaned_data.get('amount')
        current_loan_count=Transactions.objects.filter(account=self.request.user.account,transaction_type=LOAN,loan_approve=True).count()
        if current_loan_count >= 3:
            return HTTPResponse("You have exceeded the loan limit")
        
        messages.success(self.request,f"Loan Request of {amount}tk was sent successfully")
        return super().form_valid(form)
    
class TransactionReportView(LoginRequiredMixin,ListView):
    template_name='transactions/transaction_report.html'
    model=Transactions
    balance=0

    def get_queryset(self):
        queryset=super().get_queryset().filter(account=self.request.user.account)
        start_date_str=self.request.GET.get('start_date')
        end_date_str=self.request.GET.get('end_date')
        if start_date_str and end_date_str:
            start_date=datetime.strptime(start_date_str,"%Y-%m-%d").date()
            end_date=datetime.strptime(end_date_str,"%Y-%m-%d").date()
            queryset=queryset.filter(timestamp__date__gte=start_date,timestamp__date__lte=end_date)

            self.balance=Transactions.objects.filter(timestamp__date__gte=start_date,timestamp__date__lte=end_date).aggregate(Sum('amount'))['amount__sum']
        else:
            self.balance=self.request.user.account.balance
        return queryset.distinct()
    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context.update({
            'account':self.request.user.account
        })
        return context

    
class PayLoanView(LoginRequiredMixin, View):
    def get(self, request, loan_id):
        loan = get_object_or_404(Transactions, id=loan_id)
        print(loan)
        if loan.loan_approve:
            user_account = loan.account
                # Reduce the loan amount from the user's balance
                # 5000, 500 + 5000 = 5500
                # balance = 3000, loan = 5000
            if loan.amount < user_account.balance:
                user_account.balance -= loan.amount
                loan.balance_after_transaction = user_account.balance
                user_account.save()
                loan.loan_approved = True
                loan.transaction_type = LOAN_PAID
                loan.save()
                return redirect('loan_list')
            else:
                messages.error(
            self.request,
            f'Loan amount is greater than available balance'
        )

        return redirect('loan_list')
            
class LoanListView(LoginRequiredMixin,ListView):
    model=Transactions
    template_name='transactions/loan_request.html'
    context_object_name="loans" #total loan list loans ay ache

    def get_queryset(self):
        user_account = self.request.user.account
        queryset=Transactions.objects.filter(account=user_account,transaction_type=LOAN)
        return queryset

class TransferMoneyView(TransactionCreateMixin):
    form_class=TransferForm
    title='Transfer Money'

    def get_initial(self):
        initial={'transaction_type':TRANSFER }
        return initial

    def form_valid(self, form):
        amount=form.cleaned_data.get('amount')
        receiver_account_number = form.cleaned_data.get('receiver_account')
        
        try:
            receiver_account = UserBankAccount.objects.get(account_no=receiver_account_number)
        except UserBankAccount.DoesNotExist:
            form.add_error('receiver_account', 'The account does not exist.')
            return self.form_invalid(form)

        account=self.request.user.account
        account.balance-=amount
        account.save(
            update_fields=['balance']
        )
        receiver_account.balance += amount
        receiver_account.save(
            update_fields=['balance']
        )
        messages.success(self.request,f"{amount}tk was transferred successfully")
        return super().form_valid(form)
        

Module 22.5/finfriend/transactions/templates/transactions/loan_request.html
{% extends 'base.html' %}
{% block head_title %}{{ title }}{% endblock %}
{% block content %}
<div class="container my-5 py-3 px-4 bg-white rounded shadow">
  <h1 class="font-weight-bold text-center pb-3 pt-2">Loan Report</h1>
  <hr />
  <table class="table table-hover table-bordered mt-4">
    <thead class="thead-dark">
      <tr>
        <th>LOAN ID</th>
        <th>Loan Amount</th>
        <th>Loan Approved</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      {% for loan in loans %}
      <tr>
        <td>{{ loan.id }}</td>
        <td>
          <span class="badge badge-success">
            {{ loan.amount }}
          </span>
        </td>
        <td>{{ loan.loan_approve }}</td>
        <td>
          {% if loan.loan_approve %}
          <a class="btn btn-danger" href='{% url "loan_pay" loan.id %}'>Pay</a>
          {% else %}
          <p class="text-danger">Loan Pending</p>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

Module 22.5/finfriend/transactions/templates/transactions/transaction_form.html
{% extends 'base.html' %}
{% block head_title %}{{ title }}{% endblock %}
{% block content %}

<div class="d-flex justify-content-center mt-5">
    <div class="bg-white col-md-5 rounded-lg p-4">
        {% if title == 'Request For Loan' %}
        <div class="text-center mb-3">
            <a class="font-weight-bold text-primary" href="{% url 'loan_list' %}">View All Loan List</a>
        </div>
        {% endif %}
        
        <h1 class="font-weight-bold text-center pb-3">{{ title }}</h1>
        <form method="post" class="px-4 pt-3 pb-4">
            {% csrf_token %}
            
        
            <div class="mb-4">
                {% if title == 'Transfer Money' %}
                <label class="form-label" for="receiver_account">
                    Account Number
                </label>
                <input
                    class="form-control"
                    name="receiver_account" id="receiver_account" type="number" required placeholder="Account Number">
                {% endif %}
                <label class="form-label" for="amount">
                    Amount
                </label>
                <input
                    class="form-control"
                    name="amount" id="amount" type="number" required placeholder="Amount">
            </div>
            
            
            {% if form.amount.errors %} 
                {% for error in form.amount.errors %}
                <p class="text-danger small">{{ error }}</p>
                {% endfor %} 
            {% endif %}
            
            <div class="d-flex justify-content-center">
                <button class="btn btn-primary font-weight-bold" type="submit">
                    Submit
                </button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

Module 22.5/finfriend/transactions/templates/transactions/transaction_report.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block head_title %} Transaction Report{% endblock %}
{% block content %}

<div class="container my-5 py-3 px-4 bg-white rounded shadow">
  <h1 class="font-weight-bold text-center pb-3 pt-2">Transaction Report</h1>
  <hr />
  <form method="get" action="{% url 'transaction_report' %}">
    <div class="form-row justify-content-center">
      <div class="form-group col-md-3 mx-2">
        <label for="start_date">From:</label>
        <input
          class="form-control"
          type="date"
          id="start_date"
          name="start_date"
        />
      </div>
 
      <div class="form-group col-md-3">
        <label for="end_date">To:</label>
        <input
          class="form-control"
          type="date"
          id="end_date"
          name="end_date"
        />
      </div>
      <div class="form-group col-md-2">
        <button
          class="btn btn-primary mt-4"
          type="submit"
        >
          Filter
        </button>
      </div>
    </div>
  </form>
  <table class="table table-hover table-bordered mt-4">
    <thead class="thead-dark">
      <tr>
        <th>Date</th>
        <th>Transaction Type</th>
        <th>Amount</th>
        <th>Balance After Transaction</th>
      </tr>
    </thead>
    <tbody>
      {% for transaction in object_list %}
      <tr>
        <td>{{ transaction.timestamp|date:"F d, Y h:i A" }}</td>
        <td>
          <span
            class="badge {% if transaction.get_transaction_type_display == 'Withdrawal' %} badge-danger {% else %} badge-success {% endif %}"
          >
            {{ transaction.get_transaction_type_display }}
          </span>
        </td>
        <td>$ {{ transaction.amount|floatformat:2|intcomma }}</td>
        <td>$ {{ transaction.balance_after_transaction|floatformat:2|intcomma }}</td>
      </tr>
      {% endfor %}
      <tr class="table-secondary">
        <th class="text-right" colspan="3">Current Balance</th>
        <th>$ {{ account.balance|floatformat:2|intcomma }}</th>
      </tr>
    </tbody>
  </table>
</div>

{% endblock %}